# Generated by Django 2.0.8 on 2020-12-30 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text1',
            field=models.CharField(default='yate', max_length=255),
        ),
        migrations.AddField(
            model_name='image',
            name='text2',
            field=models.CharField(default='yate', max_length=255),
        ),
    ]
