# Generated by Django 2.0.8 on 2021-01-03 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
