# Generated by Django 2.0.8 on 2021-01-03 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20210103_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('text1', models.CharField(max_length=255)),
                ('body1', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cover2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('text2', models.CharField(max_length=255)),
                ('body2', models.CharField(max_length=255)),
            ],
        ),
    ]
