# Generated by Django 2.0.8 on 2021-01-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_cover3'),
    ]

    operations = [
        migrations.AddField(
            model_name='cover3',
            name='body3',
            field=models.CharField(default='yatemall', max_length=255),
        ),
    ]
