# Generated by Django 2.0.8 on 2021-01-04 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_cover3_body3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cover3',
        ),
    ]
