# Generated by Django 2.0.8 on 2021-01-05 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_cover3'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cover3',
            new_name='BrandBanner',
        ),
        migrations.RenameModel(
            old_name='Cover2',
            new_name='EventBanner',
        ),
        migrations.RenameModel(
            old_name='Cover1',
            new_name='MainBanner',
        ),
        migrations.RenameField(
            model_name='brandbanner',
            old_name='body3',
            new_name='body2',
        ),
        migrations.RenameField(
            model_name='brandbanner',
            old_name='image3',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='brandbanner',
            old_name='text3',
            new_name='text2',
        ),
        migrations.RenameField(
            model_name='eventbanner',
            old_name='body2',
            new_name='body3',
        ),
        migrations.RenameField(
            model_name='eventbanner',
            old_name='image2',
            new_name='image3',
        ),
        migrations.RenameField(
            model_name='eventbanner',
            old_name='text2',
            new_name='text3',
        ),
    ]
