# Generated by Django 2.0.8 on 2021-01-05 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_auto_20210105_0142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BrandBanner',
        ),
        migrations.DeleteModel(
            name='EventBanner',
        ),
        migrations.DeleteModel(
            name='MainBanner',
        ),
    ]
