# Generated by Django 2.0.8 on 2021-01-05 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20210105_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image2', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('text2', models.CharField(max_length=255)),
                ('body2', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='EventBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image3', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('text3', models.CharField(max_length=255)),
                ('body3', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='MainBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('text1', models.CharField(max_length=255)),
                ('body1', models.CharField(max_length=255)),
            ],
        ),
    ]
