# Generated by Django 2.0.8 on 2021-01-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_brandbanner_eventbanner_mainbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='products/%Y/%m/%d'),
        ),
    ]
