# Generated by Django 2.0.8 on 2021-01-08 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_brandtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.BrandType'),
            preserve_default=False,
        ),
    ]
