# Generated by Django 2.0.8 on 2021-01-08 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_product_brand_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand_type',
        ),
        migrations.DeleteModel(
            name='BrandType',
        ),
    ]
