# Generated by Django 2.0.8 on 2021-01-08 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_brand_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandBanner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner2image', models.ImageField(default='https://pcbonlineshop.com/var/photo/product/2000x4000/4/176/4.jpg', upload_to='covers/%Y/%m/%d')),
                ('banner2text2', models.CharField(max_length=255)),
                ('banner2body2', models.CharField(max_length=255)),
            ],
        ),
    ]
